version: '3.4'
services:
  stagingprodfrontendserver:
    env_file: .env
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/frontendserver/Dockerfile
    volumes:
      #- /frontendserverApp/build
      #- iTlAsNodeModules:/frontendserverApp/node_modules
      #- iTlFsNodeModules:/frontendServer/node_modules
      - ./certificates:/certificates/
    restart: always
    network_mode: host

  stagingprodpvserver:
    env_file: .env
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/pvserver/Dockerfile
    restart: always
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - ./certificates:/certificates/
      - ./users:/pvServer/userAuthentication/users
  stagingdemoioc:
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/demoioc/Dockerfile
    tty: true
    stdin_open: true
    restart: always
    network_mode: host
  stagingtestioc:
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/stagingioc/Dockerfile
    tty: true
    stdin_open: true
    restart: always
    network_mode: host
