version: '3.2'
services:
  stagingprodfrontendserver:
    env_file: .env
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/frontendserver/Dockerfile
    volumes:
      - ./certificates:/certificates/
    restart: always
    network_mode: host
        #ports:
    # - "80:9000"
  stagingprodpvserver:
    env_file: .env
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/pvserver/Dockerfile
    restart: always
    network_mode: host
    volumes:
      - ./certificates:/certificates/
      - ./users:/pvServer/userAuthentication/users
